INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (4, 'Cocaina', 'CNS Stimulants', 'cocaina.jpg', ' Cocaina este un stimulant puternic derivat din frunzele plantei de coca, cunoscut pentru capacitatea sa de a induce euforie și energizare rapidă. Substanța acționează prin creșterea nivelului de dopamine în creier, provocând o stare de înaltă plăcere și o energie crescută. Utilizarea sa pe termen lung poate duce la dependență severă și efecte adverse grave asupra sistemului cardiovascular și mental');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (5, 'Amfetamina', 'CNS Stimulants', 'amfetamina.jpg', 'Amfetamina este un stimulant al sistemului nervos central, utilizat pentru tratamentul ADHD (tulburarea de hiperactivitate cu deficit de atenție) și narcolepsiei. Aceasta acționează prin creșterea eliberării de neurotransmițători, cum ar fi dopaminele și norepinefrina, îmbunătățind astfel atenția și concentrarea. În plus față de utilizarea medicală, amfetamina poate fi consumată ilegal pentru efectele sale de energizare și euforizante, dar poate provoca dependență și alte probleme de sănătate.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (6, 'Metamfetamina', 'CNS Stimulants', 'metamfetamina.jpg', 'Metamfetamina este un stimulant sintetic extrem de puternic, cunoscut pentru efectele sale intense asupra sistemului nervos central. Utilizată frecvent ca drog recreațional, metamfetamina produce o euforie puternică și o stimulare crescută, dar poate duce rapid la dependență și efecte adverse grave, inclusiv deteriorarea fizică și psihologică.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (7, 'MDMA', 'CNS Stimulants,Hallucinogens', '../imaginiDroguri/MDMA.jpg', ' MDMA, cunoscută și sub numele de ecstasy, este un drog psihoactiv care induce sentimente intense de empatie, euforie și senzualitate crescută. Folosit în principal în mediul recreațional, MDMA acționează prin creșterea nivelului de serotonină în creier, provocând o stare de fericire și conectare emoțională profundă. Utilizarea excesivă a MDMA poate provoca probleme grave de sănătate, inclusiv epuizare mentală și fizică, precum și depresie severă după perioade de utilizare intensă.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (8, 'Metadona', 'Narcotic Analgesics', 'metadona.jpg', ' Metadona este un opioid sintetic utilizat în mod principal pentru tratamentul dependenței de alte opioide, cum ar fi heroina. Are efecte analgezice puternice și reduce simptomele de sevraj în cazul dependenței de opiacee. Cu toate acestea, utilizarea incorectă sau abuzul de metadonă poate duce la dependență și supradoză, cauzând efecte adverse grave asupra sistemului respirator și cardiovascular.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (9, 'Oxicodona', 'Narcotic Analgesics', 'oxicodon.jpg', 'Oxicodona este un opioid semisintetic extrem de puternic, folosit pentru tratamentul durerii moderate până la severe. Este disponibilă sub diverse forme, inclusiv tablete cu eliberare prelungită pentru gestionarea durerii cronice. Oxicodona acționează prin legarea receptorilor opioidi din creier și măduva spinării, oferind un efect analgezic puternic. Cu toate acestea, utilizarea sa incorectă sau abuzul poate duce la dependență rapidă și riscul de supradoză fatală.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (10, 'Morfina', 'Narcotic Analgesics', 'morfina.jpg', 'Morfina este un opioid natural derivat din opiu, utilizat pentru tratarea durerii severe și pentru gestionarea simptomelor în îngrijirea paliativă. Acționează prin legarea receptorilor opioidi din creier, reducând senzațiile de durere și oferind o ameliorare rapidă a suferinței fizice intense. Utilizarea pe termen lung poate duce la toleranță și dependență, fiind necesară o administrare atent monitorizată în scopuri medicale.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (11, 'Opiu', 'Narcotic Analgesics', 'opiu.jpg', ' Opiul este un extract natural din semințele plantei de mac, cunoscut pentru proprietățile sale sedative și analgezice. Utilizat în mod tradițional pentru alinarea durerii și calmarea anxietății, opiul poate provoca dependență fizică și psihologică severă în cazul utilizării regulate sau abuzive.
');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (12, 'LSD', 'Hallucinogens', 'lsd.jpg', 'LSD este un drog psihedelic extrem de potent, cunoscut pentru capacitatea sa de a provoca halucinații și modificări profunde ale percepției și gândirii. Acționează prin influențarea receptorilor serotoninici din creier, inducând experiențe vizuale și senzoriale intense. Utilizarea LSD în mediul recreațional este ilegală în majoritatea țărilor și poate duce la efecte psihologice negative severe și riscuri imprevizibile pentru sănătatea mentală.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (13, 'Codeina', 'Narcotic Analgesics', 'codeina.jpg', ' Codeina este un opioid utilizat frecvent pentru tratarea durerii moderate și suprimarea tusei. Are proprietăți analgezice și antitusive, acționând prin transformarea în morfină în organism. Utilizată în mod corect, codeina poate fi eficientă în gestionarea simptomelor, dar poate provoca dependență și alte efecte adverse grave în cazul abuzului sau utilizării necontrolate.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (14, 'Ciuperci halucinogene', 'Hallucinogens,Dissociative Anesthetics', 'ciuperciHalucinogene.jpg', ' Ciupercile halucinogene conțin compuși psihoactivi, cum ar fi psilocibina, care provoacă halucinații și schimbări profunde în percepție, gândire și conștiință. Utilizate în ritualuri tradiționale sau în scopuri recreative, ciupercile halucinogene pot oferi experiențe spirituale și psihologice intense, dar pot prezenta și riscuri semnificative pentru sănătatea mentală și fizică.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (15, 'Canabinoizi sintetici', 'Hallucinogens,Cannabis', 'canabinoiziSintetici.jpg', 'Canabinoizii sintetici sunt substanțe chimice create pentru a imita efectele canabisului natural. Sunt adesea utilizate pentru recreere sau scopuri medicinale, dar pot fi și extrem de periculoase din cauza variabilității compoziției lor și a efectelor secundare imprevizibile. Aceste substanțe au fost asociate cu incidente grave de sănătate mentală și fizică în rândul utilizatorilor.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (16, 'Catinone', 'CNS Stimulants,Cannabis', 'catinoe.jpg', 'Catinonele sunt substanțe stimulatoare care acționează asupra sistemului nervos central. Ele sunt cunoscute pentru capacitatea lor de a induce stări de euforie și energizare intensă, fiind uneori utilizate în mod ilegal pentru a spori performanța fizică sau pentru recreere. Utilizarea lor poate duce la dependență și poate avea efecte adverse grave asupra sănătății fizice și mentale.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (17, '2C-X', 'Hallucinogens', '2c-x.jpg', '2C-X reprezintă o clasă de compuși halucinogeni sintetici, cunoscuți pentru proprietățile lor psihotrope puternice. Aceste substanțe au efecte variate asupra perceptiei și stării de spirit, fiind utilizate adesea pentru experiențe de explorare mentală și spirituală. Totuși, utilizarea lor poate fi periculoasă din cauza riscului de supradoză și a efectelor secundare severe.
');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (18, 'Petidina', 'CNS Stimulants,Hallucinogens,Narcotic Analgesics,Inhalants', 'petidina.jpg', 'Petidina este un opioid sintetic utilizat pentru managementul durerii moderate până la severe. Ea acționează prin legarea receptorilor opioidi din creier, oferind un efect analgezic puternic. Cu toate acestea, petidina prezintă un risc ridicat de dependență și poate provoca efecte secundare periculoase, cum ar fi depresia respiratorie și probleme gastrointestinale.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (19, 'Fentanyl', 'Narcotic Analgesics', 'fentanyl.jpg', 'Fentanylul este un opioid sintetic extrem de puternic, folosit în principal pentru gestionarea durerii severe, cum ar fi în cazurile de cancer avansat sau după operații majore. Comparativ cu alte opioide, fentanylul este de 50 până la 100 de ori mai puternic. Utilizarea sa incorectă sau abuzul de fentanyl poate duce rapid la supradoză și deces din cauza depresiei severe a sistemului nervos central.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (20, 'Dihidrocodeina', 'Narcotic Analgesics', 'dihidrocodeina.jpg', 'Dihidrocodeina este un opioid semisintetic utilizat pentru a trata durerea moderată până la severă. Similar cu alte opioide, dihidrocodeina acționează prin legarea receptorilor opioidi din creier pentru a bloca senzațiile de durere și pentru a induce o ușurare a disconfortului. Utilizarea excesivă poate duce la dependență și poate provoca efecte secundare cum ar fi greața, amețelile și depresia respiratorie.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (21, 'Triptamine', 'CNS Depressant,Hallucinogens,Dissociative Anesthetics,Narcotic Analgesics,Inhalants', 'triptamine.jpg', 'Triptaminele sunt o clasă de compuși halucinogeni și psihedelici care sunt prezente în mod natural în organismul uman și în unele plante. Aceste substanțe pot fi și sintetizate în mod artificial și au capacitatea de a produce modificări profunde ale percepției, ale stării de spirit și ale conștiinței. Utilizarea lor este asociată cu experiențe vizuale și senzoriale intense, dar și cu riscuri semnificative pentru sănătatea mentală și fizică.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (22, 'ALTELE', 'CNS Depressant,CNS Stimulants,Hallucinogens,Dissociative Anesthetics,Narcotic Analgesics,Inhalants,Cannabis', 'altele.jpg', 'Termenul "ALTELE" se referă la alte substanțe psihoactive sau narcotice care nu sunt incluse în categoriile definite anterior. Acestea pot include o varietate de substanțe chimice și plante care au efecte psihoactive sau sedative, dar care nu sunt suficient de cunoscute sau nu sunt incluse în listele specifice de substanțe.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (23, 'Canabis', 'Hallucinogens,Cannabis', 'canabis.jpg', 'Canabisul este o plantă cunoscută pentru compușii săi activi, cum ar fi THC (tetrahidrocannabinol) și CBD (cannabidiol), care au efecte psihoactive și terapeutice. Folosit în principal pentru scopuri recreative și medicinale, canabisul poate induce stări de euforie, relaxare și stimulare a apetitului. Cu toate acestea, utilizarea excesivă poate afecta memoria, coordonarea și funcțiile cognitive.
');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (24, 'Rezina de canabis', 'CNS Depressant,CNS Stimulants,Hallucinogens,Narcotic Analgesics,Cannabis', 'rezinaDeCanabis.jpg', 'Rezina de canabis, cunoscută și sub numele de hasis, este o substanță concentrată obținută din rășina glandelor de pe planta de canabis. Are concentrații ridicate de THC și poate fi consumată prin fumare sau vaporizare pentru a produce efecte psihotrope intense. Utilizarea sa este asociată cu riscuri pentru sănătatea pulmonară și mentală.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (25, 'Ulei de canbis', 'CNS Depressant,Dissociative Anesthetics,Narcotic Analgesics,Cannabis', 'uleiDeCanabis.jpg', 'Uleiul de canabis este o formă concentrată de canabis extras din planta de canabis, care conține compuși activi precum THC și CBD. Este utilizat pentru diverse scopuri medicinale, cum ar fi gestionarea durerii, reducerea inflamației și tratarea convulsiilor. Utilizarea sa este controversată din cauza reglementărilor legale și a preocupărilor legate de efectele sale asupra sănătății mintale.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (26, 'Solutie cu THC', 'CNS Stimulants,Dissociative Anesthetics,Inhalants', 'solutieCuThc.jpg', 'Soluțiile cu THC sunt preparate lichide care conțin THC, principala substanță psihoactivă din canabis. Aceste soluții sunt adesea utilizate pentru administrare orală sau sublinguală și au efecte rapide și puternice asupra stării de spirit și ale percepției. Utilizarea lor necesită o atenție deosebită din cauza concentrației ridicate de THC și a potențialului de abuz.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (27, 'Ketamina', 'Dissociative Anesthetics', 'ketamina.jpg', 'Ketamina este un anestezic intravenos și un drog de disociere, utilizat pentru efectele sale analgezice și anestezice. Este cunoscută și pentru capacitatea sa de a induce stări de disociere, halucinații și schimbări ale percepției timpului și spațiului. Utilizarea necontrolată a ketaminei poate duce la dependență și poate provoca efecte secundare grave asupra sănătății mintale și fizice.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (28, 'Benzodiazepine', 'CNS Depressant', 'benzodiazepina.jpg', 'Benzodiazepinele sunt o clasă de medicamente cu efecte anxiolitice, sedative și hipnotice. Ele sunt utilizate pentru tratamentul anxietății, insomniei și altor tulburări psihiatrice. Benzodiazepinele acționează prin creșterea activității neurotransmițătorului GABA, reducând excitabilitatea neuronilor în creier. Utilizarea lor pe termen lung poate duce la dependență fizică și psihologică, iar întreruperea bruscă poate provoca sindrom de abstinență.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (29, 'Barbiturice', 'CNS Depressant', '../imaginiDroguri/Barbiturice.jpg', 'Barbituricele sunt medicamente sedative și hipnotice utilizate pentru tratamentul insomniei și al altor condiții neurologice și psihiatrice. Acționează prin depresia activității sistemului nervos central, inducând relaxare și somnolență. Utilizarea lor este limitată din cauza riscului de supradoză și de dependență, precum și din cauza efectelor secundare grave asupra sistemului respirator și cardiovascular.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (30, 'Zolpidem', 'CNS Depressant,CNS Stimulants', 'zolpidem.jpg', 'Zolpidemul este un medicament hipnotic utilizat pentru tratamentul insomniei severe. Acționează prin legarea receptorilor GABA din creier, reducând timpul necesar pentru a adormi și îmbunătățind calitatea somnului. Utilizarea necontrolată sau prelungită a zolpidemului poate duce la dependență și poate provoca efecte secundare cum ar fi amețelile, amnezie temporară și comportamente anormale în timpul somnului.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (31, 'Amfepramona', 'CNS Stimulants,Hallucinogens,Dissociative Anesthetics', 'amfrepramona.jpg', ' Amfepramona însăși nu prezintă afinitate pentru transportorii de monoamine și funcționează în schimb ca un promedicament pentru etcatinonă. Etcatinona (și, prin urmare, amfepramona) este un compus dopaminergic și serotoninergic foarte slab, dar aproximativ de 10 ori și 20 de ori mai puternic în ceea ce privește norepinefrina, respectiv1');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (32, 'Masa plante de cannabis', 'CNS Depressant,Hallucinogens,Cannabis', 'masaPlanteDeCanabis.jpg', 'Germinarea semințelor (3 până la 10 zile):
Semințele de cannabis trebuie să fie plasate într-un mediu cald, umed și întunecat.
Când se deschide și apare prima rădăcină albă, semințele pot fi transferate în mediul de creștere (sol, cocos etc.).
Planta va dezvolta primele două frunze ovale, numite cotiledoane.
Stadiul de plântulă (poate dura de la 2 la 3 săptămâni):
Temperatură caldă (22-27°C), umiditate relativă ridicată (65-80%) și lumină de intensitate scăzută (preferabil spectrul albastru) sunt esențiale pentru creșterea sănătoasă a plântulelor.
Stadiul vegetativ (3 până la 16 săptămâni):
Planta continuă să crească frunze și să se dezvolte.
Este important să asigurați o fotoperioadă adecvată (de obicei, 18 ore de lumină și 6 ore de întuneric).
');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (33, 'Fragmente vegetale cu THC', 'Hallucinogens', 'fragmenteVegetaleCuThc.jpg', 'Fragmentele vegetale cu THC, cunoscute și sub denumirea de muguri sau flori de cannabis, sunt părțile plantei care conțin concentrații semnificative de tetrahidrocannabinol (THC). Acest compus chimic este responsabil pentru efectele psihotrope ale cannabisului. Mugurii de cannabis sunt recoltați în timpul stadiului de înflorire al plantei, când concentrația de THC este la nivel maxim. Acești muguri pot fi uscați și apoi utilizați în diverse scopuri, cum ar fi fumatul, vaporizarea sau prepararea de alimente și băuturi infuzate cu THC. Este important să menționăm că utilizarea cannabisului trebuie să fie legală în țara sau regiunea în care se află utilizatorul. În plus, utilizarea responsabilă și informarea adecvată despre efectele și riscurile asociate sunt esențiale. ');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (37, 'Drugs', 'CNS Depressant', '../imaginiDroguri/drug.jpg', 'cadadad');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (38, 'Cactus/Mescalină', 'Hallucinogens', 'cactusMescalina.jpg', 'Mescalina este un compus psihoactiv găsit în mai multe specii de cactuși. Științific cunoscută sub denumirea de 3,4,5-trimetoxifenetilamină, mescalina este un alcaloid natural din familia fenetilaminelor. Efectele sale halucinogene și prietenoase cu mintea sunt similare cu cele ale LSD-ului, psilocibinei și DMT-ului1. Plantele care conțin mescalina au fost utilizate de populațiile indigene din Mexic, America de Sud și America Centrală timp de mii de ani. Mescalina are o afinitate ridicată pentru receptorii serotoninergici 5HT din creier și provoacă excitația neuronilor din lobul frontal. Deși nu se știe exact de ce aceste fenomene cauzează halucinații, a fost folosită tradițional de către popoarele native pentru efecte personale și sociale');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (39, 'Buprenorfină', 'Narcotic Analgesics', 'buprenofrina.jpg', 'Buprenorfina este un analgezic opioid cu potență medie care acționează slab pe receptorii μ. Este utilizată în tratamentul dependenței de opioide (singură sau în asociere cu naloxonă) și în tratamentul durerii acute sau cronice12. Deoarece se leagă puternic de acești receptori, durata sa de acțiune este lungă. Buprenorfina este disponibilă sub diverse forme, inclusiv subcutanat (injecții cu eliberare prelungită), sublingual (tablete) și transdermic (plasturi cutanati)3');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (40, 'Mitraginină', 'Narcotic Analgesics', 'mitraginina.jpg', 'Mitraginină este un alcaloid bazat pe indol și este cel mai abundent alcaloid activ din planta asiatică Mitragyna speciosa, cunoscută sub numele de kratom1.
Concentrația totală de alcaloizi în frunzele uscate variază între 0,5 și 1,5%.
În varietățile thailandeze, mitraginina este componenta cea mai abundentă (până la 66% din totalul alcaloizilor), în timp ce 7-hidroximitraginina este un constituant minor (până la 2% din conținutul total de alcaloizi).
Consumul de mitraginină are scopuri medicinale și recreative și datează de secole, deși utilizarea timpurie era limitată în principal la țările din Asia de Sud-Est, cum ar fi Indonezia și Thailanda, unde planta crește în mod indigen.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (41, 'Drugs', 'CNS Depressant,CNS Stimulants', '../imaginiDroguri/ceva.jpg', 'dadaasa');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (42, 'bro', 'CNS Depressant,CNS Stimulants,Narcotic Analgesics', '../imaginiDroguri/funDrog.jpg', 'dadada');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (46, 'Ulei de canabis', 'CNS Depressant,CNS Stimulants,Hallucinogens,Cannabis', 'uleiDeCanabis.jpg', 'Uleiul de canabis (sau CBD) provine din planta de canabis sau, mai frecvent, din plantele de cânepă. Acesta a devenit o terapie alternativă pentru diverse afecțiuni și este folosit pentru a ameliora durerea, anxietatea și tulburările de somn1. Iată câteva beneficii ale uleiului de canabis:

Reduces anxietatea: Studiile clinice arată că CBD poate diminua nivelurile de anxietate, ajutând persoanele să ducă o viață mai liniștită.
Induces sleep: Uleiul de canabis este folosit ca adjuvant pentru inducerea și menținerea unui somn linistit.
Alleviates pain: Poate reduce durerile articulare și inflamația cauzată de artrită, fiind aplicat pe piele. De asemenea, poate inhiba durerea neuropatică1.');
INSERT INTO projectdb.drugstable (id, name, type, image, description) VALUES (47, 'Plante', 'Hallucinogens', 'masaPlanteDeCanabis.jpg', 'Germinarea semințelor (3 până la 10 zile):
Semințele de cannabis trebuie să fie plasate într-un mediu cald, umed și întunecat.
Când se deschide și apare prima rădăcină albă, semințele pot fi transferate în mediul de creștere (sol, cocos etc.).
Planta va dezvolta primele două frunze ovale, numite cotiledoane.
Stadiul de plântulă (poate dura de la 2 la 3 săptămâni):
Temperatură caldă (22-27°C), umiditate relativă ridicată (65-80%) și lumină de intensitate scăzută (preferabil spectrul albastru) sunt esențiale pentru creșterea sănătoasă a plântulelor.
Stadiul vegetativ (3 până la 16 săptămâni):
Planta continuă să crească frunze și să se dezvolte.
Este important să asigurați o fotoperioadă adecvată (de obicei, 18 ore de lumină și 6 ore de întuneric).
');
