INSERT INTO projectdb.grupari_infractionale (id, categorie, numar_persoane, year, numar_grupari) VALUES (1, 'Grupări de crimă organizată', 500, 2020, 20);
INSERT INTO projectdb.grupari_infractionale (id, categorie, numar_persoane, year, numar_grupari) VALUES (2, 'Grupări de contrabandiști', 300, 2020, 15);
INSERT INTO projectdb.grupari_infractionale (id, categorie, numar_persoane, year, numar_grupari) VALUES (3, 'Grupări de crimă organizată', 600, 2021, 25);
INSERT INTO projectdb.grupari_infractionale (id, categorie, numar_persoane, year, numar_grupari) VALUES (4, 'Grupări de contrabandiști', 350, 2021, 18);
INSERT INTO projectdb.grupari_infractionale (id, categorie, numar_persoane, year, numar_grupari) VALUES (5, 'Grupări de crimă organizată', 700, 2022, 30);
INSERT INTO projectdb.grupari_infractionale (id, categorie, numar_persoane, year, numar_grupari) VALUES (6, 'Grupări de contrabandiști', 400, 2022, 20);
INSERT INTO projectdb.grupari_infractionale (id, categorie, numar_persoane, year, numar_grupari) VALUES (7, 'Grupări de crimă organizată', 800, 2023, 35);
INSERT INTO projectdb.grupari_infractionale (id, categorie, numar_persoane, year, numar_grupari) VALUES (8, 'Grupări de contrabandiști', 450, 2023, 22);
INSERT INTO projectdb.grupari_infractionale (id, categorie, numar_persoane, year, numar_grupari) VALUES (9, 'Grupări de crimă organizată', 900, 2024, 40);
INSERT INTO projectdb.grupari_infractionale (id, categorie, numar_persoane, year, numar_grupari) VALUES (10, 'Grupări de contrabandiști', 500, 2024, 25);
